# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Android example apps.
  - package-ecosystem: "gradle"
    directories:
      - /example/android/app
    commit-message:
        prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "autosubmit"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Android packages (excluding example apps).
  - package-ecosystem: "gradle"
    directories:
      - /android
    commit-message:
        prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "autosubmit"
    groups:
      test-dependencies:
        patterns:
          - "androidx.test:*"
          - "io.mockk:*"
          - "junit:junit"
          - "org.mockito:*"
          - "org.robolectric:*"
      kotlin-gradle-plugin:
        patterns:
          - "org.jetbrains.kotlin:kotlin-gradle-plugin"
      gradle-plugin:
        patterns:
          - "com.android.tools.build:gradle"
      androidx:
        patterns:
          - "androidx.annotation:annotation"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "junit:junit"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "androidx.test:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.robolectric:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "io.mockk:mockk:*"
        update-types: ["version-update:semver-patch"]
